import { Icon, Badge } from '../ui/index.jsx';

const KIND = { text: '📝 Text', image: '🖼️ Image', audio: '🔊 Audio' };

export default function Prompt({ game, q }) {
  const p = q.prompt || {};
  switch (game) {
    case 'phish':
      return (
        <div className={`msg msg--${p.channel === 'Email' ? 'email' : 'sms'}`}>
          <div className="msg__bar"><Badge>{p.channel}</Badge><span className="muted">{p.from}</span></div>
          {p.subject && <strong className="msg__subject">{p.subject}</strong>}
          <p>{p.body}</p>
          {p.attachment && <span className="msg__file">📎 {p.attachment}</span>}
          {p.link && <code className="msg__link">{p.link}</code>}
          {p.note && <p className="msg__note">Context: {p.note}</p>}
        </div>
      );
    case 'fallacy':
      return <figure className="quote"><span className="eyebrow">What is wrong?</span><blockquote>“{p.statement}”</blockquote></figure>;
    case 'human':
      return (
        <div className="scene">
          <span className="eyebrow">{p.speaker} says</span>
          <div className="bubble bubble--them scene__line"><p>{p.line}</p></div>
          <span className="eyebrow">You respond</span>
        </div>
      );
    case 'science':
      return <div className="sciq"><span className="sciq__emoji" aria-hidden="true">{p.emoji}</span><p className="muted">{p.setup}</p><h3>{p.ask}</h3></div>;
    case 'aihuman':
      return (
        <div className="aiq">
          <div className="row"><Badge tone="accent">{KIND[p.kind] || KIND.text}</Badge></div>
          <blockquote>{p.content}</blockquote>
          {p.evidence && <p className="msg__note">Evidence: {p.evidence}</p>}
          <strong>Was this generated by AI?</strong>
        </div>
      );
    case 'logic':
      return (
        <div className="logicq">
          <ol className="chain">{p.premises.map((x, i) => <li key={i}><span className="chain__node">{x}</span>{i < p.premises.length - 1 && <Icon name="chevron" size={16} />}</li>)}</ol>
          <h3>{p.ask}</h3>
        </div>
      );
    case 'money':
    case 'history':
      return <div className="sciq"><p className="muted">{p.setup}</p><h3>{p.ask}</h3></div>;
    default:
      return <div className="sciq"><h3>{q.question}</h3></div>;
  }
}
